import streamlink
from concurrent.futures import ThreadPoolExecutor

# =========================================================================
# CONFIGURATION & STATIC SOURCES
# =========================================================================
DAILYMOTION_ITEMS = [
    {"title": "Mohon Doa Restu", "id": "x9qtlim", "genres": "Comedy", "type": "movie", "logo": "https://image.tmdb.org/t/p/original/4q8Q0GQS9v2ZeMJnNiq0Its8SE7.jpg"},
    {"title": "Laura", "id": "x9f73iq", "genres": "Drama", "type": "movie", "logo": "https://image.tmdb.org/t/p/original/zVZIcXVMFdbzTTHOThrZX7o2DO7.jpg"},
    {"title": "Tujuh Hari Untuk Keshia", "id": "x9d736m", "genres": "Drama", "type": "movie", "logo": "https://image.tmdb.org/t/p/original/GnCJef0y75lyvI6AVRbRCaqWSi.jpg"},
    {"title": "Lovely Man", "id": "x917hi4", "genres": "Drama", "type": "movie", "logo": "https://image.tmdb.org/t/p/original/2DpL6GyMRJEf6bgGvyWoyQeYlzu.jpg"},
    {"title": "Father's Haunted House", "id": "x9icyxk", "genres": "Comedy", "type": "movie", "logo": "https://image.tmdb.org/t/p/original/qwfVe3no1A2sWtvP2tjYnsEe52i.jpg"},
    {"title": "Merindu Cahaya De Amstel", "id": "x9a27nu", "genres": "Romance", "type": "movie", "logo": "https://image.tmdb.org/t/p/original/uxD1hucihvTToMEoK9HCKkEQiq4.jpg"},
    {"title": "Pasutri Gaje", "id": "x9kg0yi", "genres": "Comedy", "type": "movie", "logo": "https://image.tmdb.org/t/p/original/lY6Y2wNzOgSyLJrE8rzf8QmKZpG.jpg"}
]

# Tautan HLS M3U8 Resmi Qazaqstan (100% Dapat Diputar di OTT Navigator tanpa Proxy/Worker)
QAZAQSTAN_STATIC_ITEMS = [
    {
        "title": "Qazaqstan TV Live Stream",
        "url": "https://live-qazaqstan.rtrk.kz/hls/qazaqstan/index.m3u8",
        "logo": "https://qazaqstan.tv/assets/images/logo.png",
        "genre": "General",
        "type": "channel"
    },
    {
        "title": "Balapan TV Live",
        "url": "https://live-balapan.rtrk.kz/hls/balapan/index.m3u8",
        "logo": "https://qazaqstan.tv/assets/images/logo.png",
        "genre": "Kids",
        "type": "channel"
    },
    {
        "title": "Qazsport Live",
        "url": "https://live-qazsport.rtrk.kz/hls/qazsport/index.m3u8",
        "logo": "https://qazaqstan.tv/assets/images/logo.png",
        "genre": "Sports",
        "type": "channel"
    },
    {
        "title": "Abai TV Live",
        "url": "https://live-abaitv.rtrk.kz/hls/abaitv/index.m3u8",
        "logo": "https://qazaqstan.tv/assets/images/logo.png",
        "genre": "Documentary",
        "type": "channel"
    }
]

SL_SESSION = streamlink.Streamlink()
SL_SESSION.set_option("http-headers", {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Referer": "https://www.dailymotion.com/"
})

# =========================================================================
# DAILYMOTION
# =========================================================================
def process_dailymotion_item(item):
    try:
        streams = SL_SESSION.streams(f"https://www.dailymotion.com/video/{item['id']}")
        if "best" in streams:
            url = streams['best'].url
            meta = f'#EXTINF:-1 vod="1" type="{item.get("type", "movie")}" content-type="{item.get("type", "movie")}" tvg-logo="{item["logo"]}" group-title="{item.get("genres", "Comedy")}",{item["title"]}'
            return meta, url
    except Exception as e:
        print(f"[ERROR DM] {item['title']}: {e}")
    return None

# =========================================================================
# MAIN GENERATOR
# =========================================================================
def generate_vod_playlist():
    print("[*] Generating Playlist...")

    m3u = [
        "<!--more-->", "<html>", "<head>", '<meta charset="utf-8">',
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<script language=\"javascript\">",
        'window.location.replace("https://sulthanpamenan.github.io/vod-playlist/");',
        "</script>", "</head></html>", "",
        "<================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ==================>",
        "<================== IF YOU FIND THIS PLAYLIST, PLEASE DO NOT SELL OR DISTRIBUTE IT FOR PERSONAL GAIN ==================>",
        "", "#EXTM3U", ""
    ]

    # 1. Tambahkan Dailymotion Movies
    print("\n--- Processing Dailymotion Movies ---")
    with ThreadPoolExecutor(max_workers=4) as executor:
        for res in executor.map(process_dailymotion_item, DAILYMOTION_ITEMS):
            if res:
                m3u.append(res[0])
                m3u.append(res[1])

    # 2. Tambahkan Stream Qazaqstan Statis
    print("\n--- Processing Qazaqstan Streams ---")
    for item in QAZAQSTAN_STATIC_ITEMS:
        meta = f'#EXTINF:-1 vod="1" type="{item["type"]}" content-type="{item["type"]}" tvg-logo="{item["logo"]}" group-title="{item["genre"]}",{item["title"]}'
        m3u.append(meta)
        m3u.append(item["url"])
        print(f"[ADDED] {item['title']}")

    # Simpan File
    with open("playlist.m3u", "w", encoding="utf-8") as f:
        f.write("\n".join(m3u))

    print("\n[SUCCESS] `playlist.m3u` generated successfully without external dependencies!")

if __name__ == "__main__":
    generate_vod_playlist()
