import asyncio
import re
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

USER_ID_TARGET = "wnctpm5uf2j"
HEADERS_SUFFIX = "|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36&Origin=https://www.dens.tv&Referer=https://www.dens.tv/"

GENRES_MOVIE = [
    {"name": "Action", "id": 8},
    {"name": "Action Adventure", "id": 2896},
    {"name": "Action Crime", "id": 3492},
    {"name": "Action Thriller", "id": 3484},
    {"name": "Comedy", "id": 56},
    {"name": "Comedy Adventure", "id": 3486},
    {"name": "Comedy Crime", "id": 3487},
    {"name": "Romantic Comedy", "id": 3482},
    {"name": "Drama", "id": 5},
    {"name": "Drama Comedy", "id": 3474},
    {"name": "Drama Mystery", "id": 2599},
    {"name": "Drama Thriller", "id": 2600},
    {"name": "Drama War", "id": 3490},
    {"name": "Romance", "id": 3481},
    {"name": "Horror & Thriller", "id": 7},
    {"name": "Thriller", "id": 3477},
    {"name": "Cerita Indonesia", "id": 5501},
    {"name": "Food & Cooking", "id": 4570},
    {"name": "Lifestyle & Travels", "id": 5764},
    {"name": "Music", "id": 5756},
    {"name": "Variety Show", "id": 4712},
    {"name": "Sports", "id": 4713},
    {"name": "Motorvision TV", "id": 1766},
    {"name": "My Cinema Europe", "id": 1908},
    {"name": "New Release", "id": 5551},
    {"name": "New Production", "id": 5544},
    {"name": "Exclusive", "id": 3774},
    {"name": "Free Content", "id": 3772},
    {"name": "Others", "id": 4559},
]

def fetch_movie_stream(movie_id):
    """Mengambil URL Stream m3u8 asli langsung dari API Dens.tv"""
    try:
        url = f"https://www.dens.tv/api/v1/movie/detail/{movie_id}"
        headers = {"User-Agent": "Mozilla/5.0", "Referer": "https://www.dens.tv/"}
        res = requests.get(url, headers=headers, timeout=10).json()
        
        # Ekstraksi URL M3U8
        stream_url = res.get("data", {}).get("stream_url", "") or res.get("data", {}).get("video_url", "")
        if stream_url:
            clean_url = stream_url.split("|")[0].strip()
            path = re.sub(r"/S\d+/[^/]+\.m3u8", "/index5.m3u8", clean_url)
            path = re.sub(r"/mnf\.m3u8", "/index5.m3u8", path)
            path = re.sub(r"/index\d+\.m3u8", "/index5.m3u8", path)
            return f"{path}?app_type=web&userid={USER_ID_TARGET}&movieid={movie_id}{HEADERS_SUFFIX}"
    except Exception:
        pass
    
    # Fallback format jika API detail terproteksi
    return f"https://op-svod.dens.tv/04/MVMCE00001/index5.m3u8?app_type=web&userid={USER_ID_TARGET}&movieid={movie_id}{HEADERS_SUFFIX}"

def collect_movies():
    print("[*] Fetching Movies catalog directly from Dens.tv API...")
    unique_movies = {}
    headers = {"User-Agent": "Mozilla/5.0", "Referer": "https://www.dens.tv/"}

    for genre in GENRES_MOVIE:
        try:
            api_url = f"https://www.dens.tv/api/v1/movie/list/genre/{genre['id']}?page=1&limit=60"
            resp = requests.get(api_url, headers=headers, timeout=10)
            if resp.status_code == 200:
                data = resp.json().get("data", [])
                for item in data:
                    m_id = str(item.get("id") or item.get("movie_id"))
                    title = item.get("title") or item.get("name")
                    # Mengambil Poster Potret Asli (Poster Vertical)
                    poster = item.get("poster_portrait") or item.get("poster") or item.get("image") or ""
                    if poster and not poster.startswith("http"):
                        poster = f"https://www.dens.tv{poster}"

                    if m_id and title and m_id not in unique_movies:
                        unique_movies[m_id] = {
                            "id": m_id,
                            "title": title.strip(),
                            "logo": poster,
                            "genre": genre["name"]
                        }
        except Exception as e:
            print(f"    [!] Fail genre {genre['name']}: {e}")

    return list(unique_movies.values())

def main():
    print("==================================================")
    print("[MOVIE GENERATOR] Fast API-Based Bulk Engine...")
    print("==================================================")

    header_content = [
        "#EXTM3U",
        "", "<html>", "<head>", '<meta charset="utf-8">',
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<script language=\"javascript\">",
        'window.location.replace("https://sulthanpamenan.github.io/vod-playlist/");',
        "</script>", "</head></html>", "",
        "<================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ==================>",
        "<================== IF YOU FIND THIS PLAYLIST, PLEASE DO NOT SELL OR DISTRIBUTE IT FOR PERSONAL GAIN ==================>",
        ""
    ]

    movies = collect_movies()
    print(f"[*] Total Movies Found: {len(movies)}")

    with open("movies.m3u", "w", encoding="utf-8") as f:
        f.write("\n".join(header_content) + "\n\n")

        for idx, item in enumerate(movies, 1):
            stream_url = fetch_movie_stream(item["id"])
            f.write(f'#EXTINF:-1 vod="1" type="movie" content-type="movie" tvg-id="{item["id"]}" tvg-name="{item["title"]}" tvg-logo="{item["logo"]}" group-title="{item["genre"]}",{item["title"]}\n')
            f.write(f"{stream_url}\n\n")
            print(f"[{idx}/{len(movies)}] [✓ SUCCESS] [{item['genre']}] {item['title']} (ID: {item['id']})")

    print("\n[SUCCESS] `movies.m3u` successfully updated!")

if __name__ == "__main__":
    main()
