import re
import requests
import urllib3
from urllib.parse import parse_qs, quote, unquote, urlencode, urlparse, urlunparse

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

USER_ID_TARGET = "wnctpm5uf2j"
HEADERS_SUFFIX = "|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36&Origin=https://www.dens.tv&Referer=https://www.dens.tv/"

# Daftar Kategori (menggunakan Genre ID dari Dens.tv)
CATEGORIES = [
    {"name": "New Production", "id": "5544", "slug": "new-production"},
    {"name": "Exclusive", "id": "3774", "slug": "exclusive"},
    {"name": "Drama", "id": "5", "slug": "drama"},
    {"name": "Horror & Thriller", "id": "7", "slug": "horror-thriller"},
    {"name": "Comedy", "id": "56", "slug": "comedy"},
    {"name": "Food & Cooking", "id": "4570", "slug": "food"},
    {"name": "Sports & Hobbies", "id": "1118", "slug": "sports-and-hobbies"},
]

HTTP_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36",
    "Referer": "https://www.dens.tv/",
    "Accept": "*/*"
}

def format_stream_url(raw_url, content_id):
    """Format URL m3u8 agar menggunakan token/userid target dan index5.m3u8"""
    if not raw_url:
        return ""
    parsed = urlparse(raw_url)
    path = re.sub(r"/S\d+/[^/]+\.m3u8", "/index5.m3u8", parsed.path)
    path = re.sub(r"/mnf\.m3u8", "/index5.m3u8", path)
    path = re.sub(r"/index\d+\.m3u8", "/index5.m3u8", path)

    query_dict = parse_qs(parsed.query)
    query_dict["app_type"] = ["web"]
    query_dict["userid"] = [USER_ID_TARGET]
    if content_id:
        query_dict["movieid"] = [str(content_id)]

    return urlunparse(parsed._replace(path=path, query=urlencode(query_dict, doseq=True)))

def get_series_by_category(cat_id, cat_slug):
    """Mengambil seluruh Series Induk dari Kategori"""
    url = f"https://www.dens.tv/movie/related/{cat_id}/{cat_slug}?page=1&limit=50&json=true"
    try:
        res = requests.get(url, headers=HTTP_HEADERS, timeout=10, verify=False)
        if res.status_code == 200:
            return res.json().get("data", {}).get("movies", [])
    except Exception as e:
        print(f"    [!] Gagal mengambil kategori {cat_slug}: {e}")
    return []

def get_episodes_by_series(series_id, series_slug):
    """Mengambil seluruh Episode dari Series Induk"""
    url = f"https://www.dens.tv/movie/series/{series_id}/{series_slug}?page=1&limit=50&json=true"
    try:
        res = requests.get(url, headers=HTTP_HEADERS, timeout=10, verify=False)
        if res.status_code == 200:
            return res.json().get("data", {}).get("movies", [])
    except Exception as e:
        print(f"    [!] Gagal mengambil episode series {series_id}: {e}")
    return []

def main():
    print("==================================================")
    print("[DENS.TV SCRAPER API MURNI] Memulai Ekstraksi Data...")
    print("==================================================")

    header_content = [
        "#EXTM3U",
        "", "<html>", "<head>", '<meta charset="utf-8">',
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<script language=\"javascript\">",
        'window.location.replace("https://sulthanpamenan.github.io/vod-playlist/");',
        "</script>", "</head></html>", "",
        "<================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ==================>",
        "<================== IF YOU FIND THIS PLAYLIST, PLEASE DO NOT SELL OR DISTRIBUTE IT FOR PERSONAL GAIN ==================>",
        ""
    ]

    with open("series.m3u", "w", encoding="utf-8") as f:
        f.write("\n".join(header_content) + "\n\n")

    unique_episodes = {}
    
    for cat in CATEGORIES:
        print(f"[*] Fetching Kategori: {cat['name']}...")
        series_list = get_series_by_category(cat["id"], cat["slug"])
        
        for parent in series_list:
            p_id = parent.get("movie_id")
            p_slug = parent.get("slug")
            p_title = parent.get("title")

            if not p_id or not p_slug:
                continue

            episodes = get_episodes_by_series(p_id, p_slug)
            
            # Jika tidak ada sub-episode (single VOD), masukkan series induk itu sendiri
            if not episodes:
                episodes = [parent]

            for ep in episodes:
                ep_id = ep.get("movie_id")
                if ep_id and ep_id not in unique_episodes:
                    # Ambil link stream dari API
                    raw_stream = ep.get("extra", {}).get("stream", {}).get("play_url", "")
                    if not raw_stream:
                        raw_stream = ep.get("file", "")

                    formatted_stream = format_stream_url(raw_stream, ep_id)
                    
                    # Ambil poster portret jika ada
                    poster = ep.get("url_handle", {}).get("img_port_large", "")
                    if not poster:
                        poster = ep.get("image", "")

                    unique_episodes[ep_id] = {
                        "id": ep_id,
                        "title": ep.get("title", p_title),
                        "poster": poster,
                        "genre": cat["name"],
                        "stream": formatted_stream + HEADERS_SUFFIX
                    }

    print(f"\n[✓] Total {len(unique_episodes)} Episode Berhasil Diekstrak!")
    print("==================================================")

    count = 0
    with open("series.m3u", "a", encoding="utf-8") as f:
        for ep_id, data in unique_episodes.items():
            f.write(f'#EXTINF:-1 vod="1" type="series" content-type="series" tvg-id="{data["id"]}" tvg-name="{data["title"]}" tvg-logo="{data["poster"]}" group-title="{data["genre"]}",{data["title"]}\n')
            f.write(f'{data["stream"]}\n\n')
            count += 1
            print(f"[{count}/{len(unique_episodes)}] [✓ SUCCESS] [{data['genre']}] {data['title']}")

    print("\n==================================================")
    print(f"[SELESAI] {count} Episode Berhasil Disimpan ke series.m3u")
    print("==================================================")

if __name__ == "__main__":
    main()
