import asyncio
import re
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

USER_ID_TARGET = "wnctpm5uf2j"
HEADERS_SUFFIX = "|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36&Origin=https://www.dens.tv&Referer=https://www.dens.tv/"

CATEGORIES_SERIES = [
    {"name": "Series Utama", "id": 1113},
    {"name": "Free Streaming", "id": 1057},
    {"name": "Horror & Thriller", "id": 1120},
    {"name": "Thriller", "id": 1126},
    {"name": "Food & Cooking", "id": 1114},
    {"name": "Lifestyle & Travels", "id": 1115},
    {"name": "Music & Entertainment", "id": 1116},
    {"name": "Variety Show", "id": 1117},
    {"name": "Sports", "id": 1118},
    {"name": "Cerita Indonesia", "id": 1119},
    {"name": "Exclusive Shows", "id": 1121},
]

def fetch_series_stream(series_id):
    """Mengambil URL Stream m3u8 asli langsung dari API Dens.tv"""
    try:
        url = f"https://www.dens.tv/api/v1/movie/detail/{series_id}"
        headers = {"User-Agent": "Mozilla/5.0", "Referer": "https://www.dens.tv/"}
        res = requests.get(url, headers=headers, timeout=10).json()
        
        stream_url = res.get("data", {}).get("stream_url", "") or res.get("data", {}).get("video_url", "")
        if stream_url:
            clean_url = stream_url.split("|")[0].strip()
            path = re.sub(r"/S\d+/[^/]+\.m3u8", "/index5.m3u8", clean_url)
            path = re.sub(r"/mnf\.m3u8", "/index5.m3u8", path)
            path = re.sub(r"/index\d+\.m3u8", "/index5.m3u8", path)
            return f"{path}?app_type=web&userid={USER_ID_TARGET}&movieid={series_id}{HEADERS_SUFFIX}"
    except Exception:
        pass
    
    return f"https://op-svod.dens.tv/04/MVMCE00001/index5.m3u8?app_type=web&userid={USER_ID_TARGET}&movieid={series_id}{HEADERS_SUFFIX}"

def collect_series():
    print("[*] Fetching Series catalog directly from Dens.tv API...")
    unique_series = {}
    headers = {"User-Agent": "Mozilla/5.0", "Referer": "https://www.dens.tv/"}

    for cat in CATEGORIES_SERIES:
        try:
            api_url = f"https://www.dens.tv/api/v1/movie/list/category/{cat['id']}?page=1&limit=60"
            resp = requests.get(api_url, headers=headers, timeout=10)
            if resp.status_code == 200:
                data = resp.json().get("data", [])
                for item in data:
                    s_id = str(item.get("id") or item.get("movie_id"))
                    title = item.get("title") or item.get("name")
                    # Poster Potret Asli (Poster Vertical)
                    poster = item.get("poster_portrait") or item.get("poster") or item.get("image") or ""
                    if poster and not poster.startswith("http"):
                        poster = f"https://www.dens.tv{poster}"

                    if s_id and title and s_id not in unique_series:
                        unique_series[s_id] = {
                            "id": s_id,
                            "title": title.strip(),
                            "logo": poster,
                            "genre": cat["name"]
                        }
        except Exception as e:
            print(f"    [!] Fail category {cat['name']}: {e}")

    return list(unique_series.values())

def main():
    print("==================================================")
    print("[SERIES GENERATOR] Fast API-Based Bulk Engine...")
    print("==================================================")

    header_content = [
        "#EXTM3U",
        "", "<html>", "<head>", '<meta charset="utf-8">',
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<script language=\"javascript\">",
        'window.location.replace("https://sulthanpamenan.github.io/vod-playlist/");',
        "</script>", "</head></html>", "",
        "<================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ==================>",
        "<================== IF YOU FIND THIS PLAYLIST, PLEASE DO NOT SELL OR DISTRIBUTE IT FOR PERSONAL GAIN ==================>",
        ""
    ]

    series_list = collect_series()
    print(f"[*] Total Series Found: {len(series_list)}")

    with open("series.m3u", "w", encoding="utf-8") as f:
        f.write("\n".join(header_content) + "\n\n")

        for idx, item in enumerate(series_list, 1):
            stream_url = fetch_series_stream(item["id"])
            f.write(f'#EXTINF:-1 vod="1" type="series" content-type="series" tvg-id="{item["id"]}" tvg-name="{item["title"]}" tvg-logo="{item["logo"]}" group-title="{item["genre"]}",{item["title"]}\n')
            f.write(f"{stream_url}\n\n")
            print(f"[{idx}/{len(series_list)}] [✓ SUCCESS] [{item['genre']}] {item['title']} (ID: {item['id']})")

    print("\n[SUCCESS] `series.m3u` successfully updated!")

if __name__ == "__main__":
    main()
