import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import parse_qs, quote, unquote, urlencode, urlparse, urlunparse
import requests
import urllib3
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

USER_ID_TARGET = "wnctpm5uf2j"
TMDB_API_KEY = "f5b601ec011f9760c7fb6752670714cf"
HEADERS_SUFFIX = "|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36&Origin=https://www.dens.tv&Referer=https://www.dens.tv/"

CATEGORIES = [
    {"name": "New Production", "id": "5544", "slug": "new-production"},
    {"name": "New Release", "id": "5551", "slug": "new-release"},
    {"name": "Exclusive", "id": "3774", "slug": "exclusive"},
    {"name": "Drama", "id": "5", "slug": "drama"},
    {"name": "Horror & Thriller", "id": "7", "slug": "horror-thriller"},
    {"name": "Comedy", "id": "56", "slug": "comedy"},
    {"name": "Cerita Indonesia", "id": "5501", "slug": "cerita-indonesia"},
    {"name": "Food & Cooking", "id": "4570", "slug": "food"},
    {"name": "Lifestyle & Travels", "id": "5764", "slug": "lifestyle-travels"},
    {"name": "Music", "id": "5756", "slug": "music"},
    {"name": "Variety Show", "id": "4712", "slug": "variety-show"},
    {"name": "Sports & Hobbies", "id": "1118", "slug": "sports-and-hobbies"},
]

SESSION_DENSTV = requests.Session()
SESSION_DENSTV.verify = False
adapter_dens = HTTPAdapter(pool_connections=20, pool_maxsize=20)
SESSION_DENSTV.mount("https://", adapter_dens)
SESSION_DENSTV.mount("http://", adapter_dens)

SESSION_DENSTV.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Referer": "https://www.dens.tv/",
    "Accept": "*/*"
})

def fetch_tmdb_id(title, media_type="tv"):
    if not TMDB_API_KEY or TMDB_API_KEY == "f5b601ec011f9760c7fb6752670714cf":
        return ""
    try:
        clean_title = re.sub(r'\s*\(.*?\)', '', title).strip()
        url = f"https://api.themoviedb.org/3/search/{media_type}"
        params = {"api_key": TMDB_API_KEY, "query": clean_title}
        res = requests.get(url, params=params, timeout=5)
        if res.status_code == 200:
            results = res.json().get("results", [])
            if results:
                return str(results[0].get("id", ""))
    except Exception:
        pass
    return ""

def format_stream_url(raw_url, content_id):
    if not raw_url:
        return ""
    parsed = urlparse(raw_url)
    path = re.sub(r"/S\d+/[^/]+\.m3u8", "/index5.m3u8", parsed.path)
    path = re.sub(r"/mnf\.m3u8", "/index5.m3u8", path)
    path = re.sub(r"/index\d+\.m3u8", "/index5.m3u8", path)

    query_dict = parse_qs(parsed.query)
    query_dict["app_type"] = ["web"]
    query_dict["userid"] = [USER_ID_TARGET]
    if content_id:
        query_dict["movieid"] = [str(content_id)]

    return urlunparse(parsed._replace(path=path, query=urlencode(query_dict, doseq=True)))

def get_series_by_category(cat_id, cat_slug):
    all_series = []
    page = 1
    while True:
        url = f"https://www.dens.tv/movie/related/{cat_id}/{cat_slug}?page={page}&limit=50&json=true"
        try:
            res = SESSION_DENSTV.get(url, timeout=10)
            if res.status_code == 200:
                data = res.json().get("data", {})
                series = data.get("movies", []) or data.get("series", [])
                if not series:
                    break
                all_series.extend(series)
                page += 1
            else:
                break
        except Exception:
            break
    return all_series

def get_episodes_by_series(series_id, series_slug):
    all_episodes = []
    page = 1
    while True:
        url = f"https://www.dens.tv/movie/series/{series_id}/{series_slug}?page={page}&limit=50&json=true"
        try:
            res = SESSION_DENSTV.get(url, timeout=10)
            if res.status_code == 200:
                episodes = res.json().get("data", {}).get("movies", [])
                if not episodes:
                    break
                all_episodes.extend(episodes)
                page += 1
            else:
                break
        except Exception:
            break
    return all_episodes

def main():
    print("==================================================")
    print("[SERIES GENERATOR] With Auto-TMDB & Full Categories")
    print("==================================================")

    header_content = [
        "#EXTM3U",
        "", "<html>", "<body>", '<meta charset="utf-8">',
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<script language=\"javascript\">",
        'window.location.replace("https://sulthanpamenan.github.io/vod-playlist/");',
        "</script>", "</body></html>", "",
        "<================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ==================>",
        "<================== IF YOU FIND THIS PLAYLIST, PLEASE DO NOT SELL OR DISTRIBUTE FOR PERSONAL GAIN ==================>",
        ""
    ]

    with open("series.m3u", "w", encoding="utf-8") as f:
        f.write("\n".join(header_content) + "\n\n")

    unique_episodes = {}
    tmdb_cache = {}

    for cat in CATEGORIES:
        print(f"[*] Fetching category: {cat['name']}...")
        series_list = get_series_by_category(cat["id"], cat["slug"])
        
        for parent in series_list:
            p_id = parent.get("movie_id")
            p_title = parent.get("title", "")
            if not p_id:
                continue

            if p_title not in tmdb_cache:
                tmdb_cache[p_title] = fetch_tmdb_id(p_title, "tv")
            parent_tmdb_id = tmdb_cache[p_title]

            episodes = get_episodes_by_series(p_id, parent.get("slug", ""))
            if not episodes:
                episodes = [parent]

            for idx, ep in enumerate(episodes, start=1):
                ep_id = ep.get("movie_id")
                if ep_id and ep_id not in unique_episodes:
                    raw_stream = ep.get("extra", {}).get("stream", {}).get("play_url", "") or ep.get("file", "")
                    formatted_stream = format_stream_url(raw_stream, ep_id)
                    poster = ep.get("url_handle", {}).get("img_port_large", "") or ep.get("image", "")
                    ep_title = ep.get("title", p_title)
                    season_num = str(ep.get("season", 1)) if ep.get("season") else "1"
                    episode_num = str(ep.get("episode", idx)) if ep.get("episode") else str(idx)

                    if formatted_stream:
                        unique_episodes[ep_id] = {
                            "title": ep_title,
                            "serie_title": p_title,
                            "tmdb_id": parent_tmdb_id,
                            "poster": poster,
                            "genre": cat["name"],
                            "season": season_num,
                            "episode": episode_num,
                            "stream": formatted_stream + HEADERS_SUFFIX
                        }

    count = 0
    with open("series.m3u", "a", encoding="utf-8") as f:
        for item_key, data in unique_episodes.items():
            formatted_line_title = f"{data['serie_title']} S0{data['season']}E0{data['episode']} - {data['title']}" if len(data['episode']) == 1 else f"{data['serie_title']} S0{data['season']}E{data['episode']} - {data['title']}"
            
            f.write(f'#EXTINF:-1 vod="1" type="series" content-type="series" tvg-tmdb="{data["tmdb_id"]}" serie-title="{data["serie_title"]}" tvg-season="{data["season"]}" tvg-episode="{data["episode"]}" tvg-logo="{data["poster"]}" group-title="{data["genre"]}",{formatted_line_title}\n')
            f.write(f'{data["stream"]}\n\n')
            count += 1
            print(f"[{count}] [✓] {formatted_line_title} (TMDB: {data['tmdb_id'] or 'Not Found'})")

    print("\n[COMPLETED] series.m3u Successfully Updated!")

if __name__ == "__main__":
    main()
